name: cf-scripts
channels:
  - conda-forge
dependencies:
 - attrs
 - backoff
 - black
 - boto3
 - cachecontrol
 - cachetools
 - conda
 - conda-forge-feedstock-check-solvable>=0.3.0
 - conda-forge-pinning
 - conda-libmamba-solver
 - conda-forge-metdata>=0.3.0
 - conda-package-handling<2
 - conda-smithy
 - curl
 - depfinder
 - distributed
 - doctr
 - feedparser
 - frozendict
 - git
 - github3.py
 - grayskull
 - jinja2
 - lockfile
 - mamba>=0.23
 - msgpack-python
 - networkx!=2.8.1
 - packaging
 - psutil
 - pygithub
 - pynamodb
 - python-dateutil
 - python-graphviz
 - python-rapidjson
 - requests
 - rever
 - ruamel.yaml
 - ruamel.yaml.jinja2
 - scipy
 - setuptools<66
 - stopit
 - streamz
 - tar
 - tqdm
 - wurlitzer
 - yaml
 - pandas
 - xonsh
