name: cf-scripts
channels:
  - conda-forge
platforms:
  - osx-arm64
  - linux-64
  - osx-64
dependencies:
  - attrs
  - backoff
  - bcrypt
  - cachecontrol
  - cachetools
  - click
  - conda
  - conda-lock
  - conda-forge-feedstock-check-solvable >=0.8.0
  - conda-forge-feedstock-ops >=0.12.0
  - conda-forge-pinning
  - conda-libmamba-solver
  - conda-forge-metadata >=0.3.0
  - conda-package-handling
  - conda-smithy >=3.34.1
  - conda-build >=3.24.0
  - conda-recipe-manager >=0.6.1
  - curl
  - depfinder
  - distributed
  - fastapi
  - feedparser
  - frozendict
  - git <2.50
  - github3.py
  - grayskull >=2.5
  - jinja2
  - lockfile
  - mamba >=0.23
  - mitmproxy
  - msgpack-python
  - networkx !=2.8.1
  - numpy
  - orjson
  - packaging
  - psutil
  - pydantic
  - pydantic-extra-types
  - pydantic-settings
  - pygithub
  - pymongo
  - pynamodb
  - python=3.11
  - python-dateutil
  - python-graphviz
  - rattler-build >=0.35.4
  - rattler-build-conda-compat >=1.3.0,<2
  - requests
  - ruamel.yaml
  - ruamel.yaml.jinja2
  - scipy
  - setuptools
  - stopit
  - streamz
  - tar
  - tqdm
  - wget
  - wurlitzer
  - yaml
  - pip
  - pytest <8.1.0
  - pytest-xprocess
  - codecov
  - requests-mock
  - pre-commit
  - pytest-xdist
  - pytest-cov
  - pytest-env
  - pytest-retry
  - pytest-split
  - setuptools_scm >=8
  - python-build
  - mypy
