name: delete-old-runs
on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  workflow_dispatch: null

jobs:
  delete-old-runs:
    name: delete-old-runs
    runs-on: "ubuntu-latest"
    steps:
      - name: get env file
        shell: bash -l {0}
        run: |
          wget https://raw.githubusercontent.com/conda-forge/repodata-tools/main/environment.yml

      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main

      - name: delete runs
        shell: bash -l {0}
        run: |
          echo "\
          import github
          import os
          import sys
          import requests
          import datetime
          import time

          gh = github.Github(os.environ['GITHUB_TOKEN'])
          r = gh.get_repo('regro/autotick-bot')
          done = 0
          for w in r.get_workflows():
              for _ in range(10):
                  for rn in w.get_runs():
                      if rn.status == 'completed' and (
                          datetime.datetime.utcnow() - rn.updated_at > datetime.timedelta(days=365)
                      ):
                          requests.delete(
                              rn.url,
                              headers={'Authorization': 'Bearer ' + os.environ['GITHUB_TOKEN']},
                          )
                          done += 1
                          time.sleep(2)
                      if done == 200:
                          sys.exit(0)
          " > del_old_runs.py

          python del_old_runs.py
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOTICK_BOT_TOKEN }}
